#!/usr/bin/python3
import sys, os #, time, json, pprint
import wetsuite.helpers.localdata


if __name__ == '__main__':
    if len(sys.argv) != 3:
        sys.stderr.write( "This script takes a path and a single key\n")
        sys.exit(-1)
    else:
        path, key = sys.argv[1:]

        if not os.path.exists( path ):
            print( 'Specified path not found: %r'%path )
            sys.exit(-2)

        if not wetsuite.helpers.localdata.is_file_a_store( path ):
            print( 'Specified path does not seem to be an SQLite file create by us: %r'%path )
            sys.exit(-3)

        store = wetsuite.helpers.localdata.LocalKV(path, str, str) # the types are not actually used because we don't use put()
        count = 0
        val = store.get( key )
        store.close()
        if type(val) is bytes:
            sys.stdout.buffer.write( val )
        elif type(val) is str:
            sys.stdout.write( val )
        else:
            sys.stdout.write( str(val) )

