#!/usr/bin/python3
''' Given a path to a LocalKV or MsgPackKV style database, and a key in it, prints out the value.

    Note that this is only for debug, e.g. in that it may transform the output value to do so.
'''
import sys, os, pprint
import wetsuite.helpers.localdata

def main():
    ' see module docstring '
    if len(sys.argv) != 3:
        sys.stderr.write( "This script takes a path and a single key\n")
        sys.exit(-1)
    else:
        path, key = sys.argv[1:]

        if not os.path.exists( path ):
            print( 'Specified path not found: %r'%path )
            sys.exit(-2)

        if not wetsuite.helpers.localdata.is_file_a_store( path ):
            print( 'Specified path does not seem to be an SQLite file create by us: %r'%path )
            sys.exit(-3)

        store = wetsuite.helpers.localdata.LocalKV(path, None, None, read_only=True) # the types are not actually used because we don't use put()

        # CONSIDER: deal with msgpack more cleanly
        if store._get_meta('valtype', missing_as_none=True) == 'msgpack':
            store.close()
            store = wetsuite.helpers.localdata.MsgpackKV(path, str)

        val = store.get( key )
        store.close()
        if isinstance(val, bytes):
            sys.stdout.buffer.write( val )
        elif isinstance(val, str):
            sys.stdout.write( val )
        elif isinstance(val, dict): # assumes msgpackkv used as such
            sys.stdout.write( pprint.pformat(val) )
        else:
            sys.stdout.write( str(val) )
        sys.stdout.write( '\n' )


if __name__ == '__main__':
    main()
