#!/usr/bin/python3
''' Given one or more paths to a LocalKV style database,
    list all its keys, one per line
'''

import sys
import os

import wetsuite.helpers.localdata

def main():
    ' see module docstring '
    for path in sys.argv[1:]:
        path = os.path.abspath( path ) # mostly to avoid localdata.resolve_path interpretation
        if not os.path.exists( path ):
            print( 'Specified path not found: %r'%path )
            continue

        if not wetsuite.helpers.localdata.is_file_a_store( path ):
            print( 'Specified path does not seem to be an SQLite file created by us: %r'%path )
            continue

        sys.stderr.write( '== %r ==\n'%path )
        sys.stderr.flush()
        # materialize that list to avoid keeping the store open for longer than necessary (takes proportional amounts of RAM, though)
        # the types are not actually used because we don't use put()
        with wetsuite.helpers.localdata.LocalKV(path, None,None) as store:
            keys = list( store.iterkeys() )
        count = 0
        for key in keys:
            print(key)
            count += 1
        sys.stderr.write( '# Listed %d keys\n'%count )

if __name__ == '__main__':
    main()
