#!/usr/bin/python3
import wetsuite.helpers.localdata
import wetsuite.helpers.format


if __name__ == '__main__':
    for item in wetsuite.helpers.localdata.list_stores( True ):
        bytesize = item.pop('bytesize')
        num_items = item.pop('num_items', None)

        print('  %5sB'%wetsuite.helpers.format.kmgtp(bytesize, extradigits=0), end='')
        
        if num_items is not None:
            try:
                avg = bytesize / num_items
            except ZeroDivisionError:
                avg = 0

            print('   %9s items     %5sB/item'%(
                wetsuite.helpers.format.kmgtp(num_items, extradigits=0), 
                wetsuite.helpers.format.kmgtp(avg, extradigits=0)
                ), end='')

        description = item.pop('description', None)
        #if description is not None:
        #    print('description: %sB'%( '\n'.join(textwrap.wrap(description, 90, subsequent_indent='             '))))

           
        print('       %s'%item.pop('path'), end='')

        #if len(item) > 0:
        #    print(item, end='')

        print()
