#!/bin/bash
# Do tests.   Also calculate amount of test coverage, and wrangle that percentage into a file.


# in a py2+py3 system, pytest may be called pytest-3 for disambiguation, so prefer that 
command_exists () {
    type "$1" &> /dev/null ;
}

if command_exists pytest-3 ; then
  PYTESTCMD="pytest-3"
else
  if command_exists pytest ; then
    PYTESTCMD="pytest"
  else
     echo 'ERROR: could not find pytest.' >&2
     exit 1
  fi
fi

$PYTESTCMD --cov=wetsuite --cov-report html:coverage-report tests/ | tee >(cat >&2) | grep TOTAL | tr -s ' ' ' ' | cut -d ' ' -f 4   > coverage.txt
# --cov-report html:coverage-report tests/


